# Generated by Django 3.0.4 on 2020-07-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='dateBought',
            field=models.DateField(blank=True),
        ),
    ]
