# Generated by Django 3.0.4 on 2020-07-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0003_auto_20200715_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='insuranceEndDate',
            field=models.DateField(blank=True),
        ),
    ]
