# Generated by Django 3.0.4 on 2020-07-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0004_auto_20200715_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='productMaintenanceAlerts',
            field=models.BooleanField(default=True),
        ),
    ]
