# Generated by Django 3.0.4 on 2020-07-15 12:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0005_device_productmaintenancealerts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='productMaintenanceAlerts',
        ),
        migrations.AddField(
            model_name='device',
            name='catalogChoice',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SMS', 'SMS'), ('Email', 'Email'), ('Notification', 'Notification')], default='code', max_length=22),
        ),
    ]
