# Generated by Django 3.0.4 on 2020-07-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0006_auto_20200715_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='catalogChoice',
            new_name='productMaintenanceAlerts',
        ),
    ]
