# Generated by Django 3.0.4 on 2020-07-15 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0007_auto_20200715_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='description',
        ),
        migrations.RemoveField(
            model_name='device',
            name='isImportant',
        ),
        migrations.RemoveField(
            model_name='device',
            name='title',
        ),
    ]
