# Generated by Django 3.0.4 on 2020-07-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0008_auto_20200715_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ensuredBy',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
