# Generated by Django 3.0.4 on 2020-07-18 19:03

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0009_device_ensuredby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='dateCompleted',
        ),
        migrations.RemoveField(
            model_name='device',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='device',
            name='productMaintenanceAlerts',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SMS', 'SMS'), ('Email', 'Email'), ('Notification', 'Notification')], default='code', max_length=22, null=True),
        ),
    ]
